- name: install nginx
  hosts: node-1
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: absent
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
