- name: vars from files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: Course details
    ansible.builtin.debug:
      msg: " Course is {{ COURSE }}, and Duration is {{ DURATION }}"