- name: data types in ansible
  hosts: local
  connecton: local
  vars:
    NUMBER: 25
    STRING: "THIS IS STRING"
    BOOL: true
    LIST:
    - vignesh
    - abhi
    MAP:
      vignesh: devops
      abhi: ['hardware', 'eee']
  
  tasks:
  - name: print data types
    ansible.builtin.debug:
      msg: " {{ NUMBER }}, {{ STRING }}, {{ BOOL }}, {{ LIST }}, {{ MAP }}"